### ISSUE TITLE
Checking for new modpacks fails

### ISSUE THREAD

**Issue by kaikue** [Nincraft/Launcher#6]
The list of modpacks could not be downloaded.

To report this error, please provide:

java.io.IOException: The list of modpacks could not be downloaded.
    at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:191)
    at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:102)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection timed out: connect
    at java.net.DualStackPlainSocketImpl.connect0(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at sun.net.NetworkClient.doConnect(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.http.HttpClient.<init>(Unknown Source)
    at sun.net.www.http.HttpClient.New(Unknown Source)
    at sun.net.www.http.HttpClient.New(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
    at com.skcraft.launcher.util.HttpRequest.execute(HttpRequest.java:130)
    at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:138)
    ... 5 more

**Comment by Nincodedo** [comment]
Does this error still happen? We were having some issues with the server's internet connection earlier.

**Comment by kaikue** [comment]
It works fine now.

**Comment by Nincodedo** [comment]
Good to hear. I'll look into handling this error better.
